version: "3"
services:
  benchmark: 
    image: nclcloudcomputing/javabenchmarkapp
    deploy:
      replicas: 2 
    ports:
      - "8080:8080"
    networks: 
      - webnet 
  visual:
    image: dockersamples/visualizer
    ports:
      - "4000:8080"
    build: .
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  mongo:
    image: mongo
    ports: 
      - "3306:3306"
networks:
  webnet:
